# Generated by Django 5.0.1 on 2024-02-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_number', models.IntegerField()),
                ('emp_name', models.CharField(max_length=64)),
                ('emp_salary', models.CharField(max_length=64)),
                ('emp_address', models.CharField(max_length=164)),
            ],
        ),
    ]
